# Full config options: https://gohugo.io/getting-started/configuration/#toml-configuration
# Arranged according to use in Ananke
title = "Vedang Manerikar"
baseURL = "https://vedang.me/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "vedang"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # --------------------------------------------------
  # Params needed by Ananke
  favicon = ""
  description = "My corner on the Inter Webs."
  twitter = "https://twitter.com/vedang"
  github = "https://github.com/vedang/"
  featured_image = "/images/clevinger.jpg"
  show_reading_time = true
  #---------------------------
  # My Changes
  vedang_main_section = "techlog"
  vedang_section2 = "weblog"
  # --------------------------------------------------

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "techlog"
  name = "Techlog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-floppy-o\"></i>"
  url = "/techlog"
[[menu.main]]
  weight = 2
  identifier = "weblog"
  name = "Weblog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-text\"></i>"
  url = "/weblog"
[[menu.main]]
  weight = 3
  identifier = "mahabharat"
  name = "Mahabharat"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-podcast\"></i>"
  url = "/mahabharat"
[[menu.main]]
  weight = 4
  identifier = "recipes"
  name = "Lily's Recipes"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-cutlery\"></i>"
  url = "/recipes"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About Me"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/about/"
