# Full config options: https://gohugo.io/getting-started/configuration/#toml-configuration
baseURL = "https://vedang.me/"
languageCode = "en-us"
title = "Vedang Manerikar"
theme = "ananke"
enableRobotsTXT = true
paginate = 3
disqusShortname = "vedang"

[author]
  name = "Vedang Manerikar"
  bio = "sings badly and at the top of his voice. writes Clojure code for [@Helpshift](https://twitter.com/helpshift/). will work for chocolate."
  location = "Pune, India"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  gravatarEmail = "ved.manerikar@gmail.com"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "vedang"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "techlog"
  name = "Techlog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-floppy-o\"></i>"
  url = "/techlog"
[[menu.main]]
  weight = 2
  identifier = "weblog"
  name = "Weblog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-text\"></i>"
  url = "/weblog"
[[menu.main]]
  weight = 3
  identifier = "recipes"
  name = "Lily's Recipes"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-cutlery\"></i>"
  url = "/recipes"
[[menu.main]]
  weight = 4
  identifier = "mahabharat"
  name = "Mahabharat"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-podcast\"></i>"
  url = "/mahabharat"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About Me"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/about/"

[[menu.links]]
  weight = 1
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-twitter\"></i>"
  url = "https://twitter.com/vedang"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/vedang"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
    # --------------------------------------------------
    # Params needed by Ananke
    featured_image = "/images/peace.jpg"
    # --------------------------------------------------

    # Params needed by Manis
    # ----------
    copyright = "&copy; 2017 Vedang Manerikar"
	debugCSS = false						# If false use use minified CSS (ui.min.css)
	# Site meta description
	description = ""
	tagline = "My corner on the Inter Webs."	# Site's Tagline (Subtitle or Keyword)
	themeAttrib = true						# If true give attribution to this theme
	licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"			# URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#ff8181"					# Color of your website
	latestCount = 3							# Maximum number of item in Latest Posts or Works
	faviconImg = ""							# Path to site's favicon image
	dateFmt = "Jan 02, 2006"				# Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go", "clojure", "python" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "vedang.manerikar@gmail.com"
	github = "https://github.com/vedang/"
	twitter = "https://twitter.com/vedang"
    # ----------

    # Params needed by Tranquilpeak
    # ----------
    clearReading = true
    hierarchicalCategories = false
    sidebarBehavior = 4
    coverImage = "peace.jpg"
    thumbnailImage = true
    thumbnailImagePosition = "right"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  # Customize link of author avatar in sidebar
  [params.sidebar.profile]
    url = "/#about"

  # Customize copyright value "© 2016 <CUSTOMIZATION>. All Rights Reserved"
  [params.footer]
    copyright = "<a href=\"https://twitter.com/vedang\">Vedang Manerikar</a>"
