# Full config options: https://gohugo.io/getting-started/configuration/#toml-configuration
# Arranged according to use in Ananke
title = "Vedang Manerikar"
baseURL = "https://vedang.me/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = "UA-2086352-6"
enableRobotsTXT = true
disqusShortname = "vedang"
pygmentsCodeFences = true
disableFastRender = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xhtml = false

[params]
  # --------------------------------------------------
  # Params needed by Ananke
  favicon = "images/vedang_small.jpeg"
  description = "My corner on the Inter Webs."
  twitter = "https://twitter.com/vedang"
  github = "https://github.com/vedang"
  mastodon = "https://mastodon.technology/@vedang"
  featured_image = "/images/clevinger.jpg"
  show_reading_time = true
  recent_posts_number = 10
  #---------------------------
  # My Changes
  vedang_main_section = "blog"
  vedang_section2 = "weblog"
  # --------------------------------------------------

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "blog"
  name = "Writing"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-floppy-o\"></i>"
  url = "/blog"
[[menu.main]]
  weight = 2
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-file-text\"></i>"
  url = "/projects"
[[menu.main]]
  weight = 3
  identifier = "mahabharat"
  name = "Mahabharat"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-podcast\"></i>"
  url = "/mahabharat"
[[menu.main]]
  weight = 4
  identifier = "recipes"
  name = "Lily's Recipes"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-cutlery\"></i>"
  url = "/recipes"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About Me"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/about/"
