# Full config options: https://gohugo.io/getting-started/configuration/#toml-configuration
baseURL = "https://vedang.me/"
languageCode = "en-us"
title = "Vedang Manerikar"
theme = "ananke"
enableRobotsTXT = true
paginate = 3
[params]
    # Params needed by Manis
    # ----------
    copyright = "&copy; 2017 Vedang Manerikar"
	debugCSS = false						# If false use use minified CSS (ui.min.css)
	# Site meta description
	description = ""
	tagline = "My corner on the Inter Webs."	# Site's Tagline (Subtitle or Keyword)
	themeAttrib = true						# If true give attribution to this theme
	licenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"			# URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#ff8181"					# Color of your website
	latestCount = 3							# Maximum number of item in Latest Posts or Works
	faviconImg = ""							# Path to site's favicon image
	dateFmt = "Jan 02, 2006"				# Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go", "clojure", "python" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "vedang.manerikar@gmail.com"
	github = "https://github.com/vedang/"
	twitter = "https://twitter.com/vedang"
    # ----------
