#+hugo_base_dir: ../
#+setupfile: ./setup.org
* Projects
  :PROPERTIES:
  :CATEGORY: projects
  :END:
** DONE I have questions about COVID-19                 :covid19:coronavirus:
   CLOSED: [2020-03-23 Mon 10:10]
   :PROPERTIES:
   :EXPORT_HUGO_BUNDLE: i-have-questions-about-covid19
   :EXPORT_FILE_NAME: index
   :EXPORT_OPTIONS: num:1
   :EXPORT_HUGO_SECTION: projects
   :EXPORT_HUGO_RESOURCES: :src "hs_corona.js"
   :END:
   :LOGBOOK:
   - State "DONE"       from "TODO"       [2020-03-23 Mon 10:10]
   - State "TODO"       from              [2020-03-23 Mon 09:57]
   :END:
This page is a demo page, built to showcase how we can use bots to
answer common questions that people have about COVID-19. This is a
great way for folks to get up-to-date information about the pandemic
while staying at home.

To get started, click on the chat widget on the bottom right corner of
the screen. Follow the instructions.

This bot is built on guidelines and bots published by the World Health
Organization and the Indian Govt. The official websites are:

World Health Organization:
https://www.who.int/emergencies/diseases/novel-coronavirus-2019/events-as-they-happen

The Indian Govt: https://www.mygov.in/covid-19

If you have any questions, comments or feedback on the bot, please
email me at vedang at helpshift dot com.
#+begin_export html
<script src="hs_corona.js"></script>
#+end_export
* Tiny Logs                                                        :@tinylog:
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: blog
  :END:
** DONE Tinylog: Mbsync: Error: Channel <x> Is Locked                :mbsync:
   CLOSED: [2017-10-11 Wed 19:22]
   :PROPERTIES:
   :EXPORT_FILE_NAME: mbsync-channel-is-locked
   :END:
You may come across the following error when running ~mbsync~ :

#+begin_example
  Error: channel :<channel-name>-remote:<folder>-:<channel-name>-local:<folder> is locked
#+end_example

This happens when there is another ~mbsync~ instance running in
parallel and it has taken a lock on the particular folder. In my case,
I am running ~mbsync~ via a cron-job, and it tends to leave dead
instances around if the laptop sleeps during a run. Kill all instances
of ~mbsync~ and restart the process and you should be fine!
